### ISSUE TITLE
2020.3.47f1c1不包含DropdownField

### ISSUE THREAD

**Issue by BoyceLig** [Cyanilux/ShaderGraphVariables#9]
我是2020.3.47f1c1，ShaderGraph10.10.1，导入后报错
```
Packages\ShaderGraphVariables-main\Editor\SGVariables.cs(411,24): error CS0246: The type or namespace name 'DropdownField' could not be found (are you missing a using directive or an assembly reference?)
```
这Unity的版本没有DropdownField

**Comment by BoyceLig** [comment]
我尝试安装了`com.unity.ui`组件，但是与`com.unity.purchasing`冲突，他俩都报错了

**Comment by Cyanilux** [comment]
Heya, thanks for reporting this issue!

I didn't realise that DropdownField was not a part of UI Toolkit during 2020 so have reverted it to using input fields for that version.

I've updated the package with some fixes. Please update / reinstall under the Package Manager.

Let me know if there's any more issues :)
